name: bleatchvr
services:

  # Caddy (Webserver/Reverse Proxy)
  caddy:
    image: caddy:2.11
    container_name: bleatchvr-caddy
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"]
    volumes:
      - ./html:/app/files/html
      - ./js:/app/files/js
      - ./css:/app/files/css
      - ./images:/app/files/images
      - ./models:/app/files/models
      - ./sounds:/app/files/sounds
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8099:80"

  # Node.js (Backend API - Socket.io Server)
  nodejs:
    image: node:18-alpine
    container_name: bleatchvr-nodejs
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    restart: unless-stopped

  # Cloudflared (Proxy/Tunnel)
  cloudflared:
    image: cloudflare/cloudflared:1800-17533b124c22
    container_name: bleatchvr-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
