name: bleatchvr
services:

  # Caddy (Webserver/Reverse Proxy)
  caddy:
    image: caddy:2.11
    container_name: bleatchvr-caddy
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch"]
    volumes:
      - ./html:/app/files/html
      - ./js:/app/files/js
      - ./css:/app/files/css
      - ./images:/app/files/images
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8099:80"
      - "443:443"

  # Cloudflared (Proxy/Tunnel)
  cloudflared:
    image: cloudflare/cloudflared:1800-17533b124c22
    container_name: bleatchvr-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
